import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar for Physical AI & Humanoid Robotics textbook
  textbookSidebar: [
    {
      type: 'category',
      label: '1. The Era of Embodied Intelligence',
      items: [
        'chapters/chapter1/section1-digital-ai-to-physical-ai',
        'chapters/chapter1/section2-humanoid-form-factor',
        'chapters/chapter1/section3-safety-ethics',
        'chapters/chapter1/section4-embodied-cognition',
        'chapters/chapter1/section5-physical-reasoning',
        'chapters/chapter1/section6-benefits-challenges'
      ],
    },
    {
      type: 'category',
      label: '2. The Hardware Nervous System',
      items: [
        'chapters/chapter2/section1-sensors-lidar-cameras',
        'chapters/chapter2/section2-actuators',
        'chapters/chapter2/section3-compute-jetson-rtx',
        'chapters/chapter2/section4-power-management',
        'chapters/chapter2/section5-hardware-integration',
        'chapters/chapter2/section6-real-time-constraints'
      ],
    },
    {
      type: 'category',
      label: '3. ROS 2 Foundations',
      items: [
        'chapters/chapter3/section1-architecture',
        'chapters/chapter3/section2-nodes',
        'chapters/chapter3/section3-topics',
        'chapters/chapter3/section4-services',
        'chapters/chapter3/section5-custom-interfaces',
        'chapters/chapter3/section6-best-practices'
      ],
    },
    {
      type: 'category',
      label: '4. Robot Description & Kinematics',
      items: [
        'chapters/chapter4/section1-urdf-sdf',
        'chapters/chapter4/section2-coordinate-frames',
        'chapters/chapter4/section3-forward-inverse-kinematics',
        'chapters/chapter4/section4-joint-limits',
        'chapters/chapter4/section5-dh-parameters',
        'chapters/chapter4/section6-kinematic-calibration'
      ],
    },
    {
      type: 'category',
      label: '5. Simulation Worlds (Gazebo)',
      items: [
        'chapters/chapter5/section1-physics-engines',
        'chapters/chapter5/section2-environment-design',
        'chapters/chapter5/section3-collision-detection',
        'chapters/chapter5/section4-inertia',
        'chapters/chapter5/section5-sensor-simulation',
        'chapters/chapter5/section6-simulation-realism'
      ],
    },
    {
      type: 'category',
      label: '6. The Digital Twin (NVIDIA Isaac)',
      items: [
        'chapters/chapter6/section1-omniverse',
        'chapters/chapter6/section2-usd-assets',
        'chapters/chapter6/section3-rtx-rendering',
        'chapters/chapter6/section4-sim-to-real-gaps',
        'chapters/chapter6/section5-photorealistic-simulation',
        'chapters/chapter6/section6-digital-twin-applications'
      ],
    },
    {
      type: 'category',
      label: '7. Perception & Vision',
      items: [
        'chapters/chapter7/section1-computer-vision',
        'chapters/chapter7/section2-depth-estimation',
        'chapters/chapter7/section3-object-detection',
        'chapters/chapter7/section4-slam',
        'chapters/chapter7/section5-visual-servoing',
        'chapters/chapter7/section6-perception-fusion'
      ],
    },
    {
      type: 'category',
      label: '8. Navigation & Control',
      items: [
        'chapters/chapter8/section1-nav2-stack',
        'chapters/chapter8/section2-path-planning',
        'chapters/chapter8/section3-obstacle-avoidance',
        'chapters/chapter8/section4-pid-control',
        'chapters/chapter8/section5-motion-planning',
        'chapters/chapter8/section6-localization'
      ],
    },
    {
      type: 'category',
      label: '9. Manipulation & Grasping',
      items: [
        'chapters/chapter9/section1-moveit2',
        'chapters/chapter9/section2-grasp-planning',
        'chapters/chapter9/section3-hand-eye-calibration',
        'chapters/chapter9/section4-tactile-sensing',
        'chapters/chapter9/section5-precision-manipulation',
        'chapters/chapter9/section6-tool-use'
      ],
    },
    {
      type: 'category',
      label: '10. Agentic AI & VLA',
      items: [
        'chapters/chapter10/section1-vision-language-action-models',
        'chapters/chapter10/section2-llms-for-planning',
        'chapters/chapter10/section3-voice-control-whisper',
        'chapters/chapter10/section4-cognitive-architectures',
        'chapters/chapter10/section5-reasoning-under-uncertainty',
        'chapters/chapter10/section6-human-robot-interaction'
      ],
    },
    {
      type: 'category',
      label: '11. Capstone: The Autonomous Humanoid',
      items: [
        'chapters/chapter11/section1-integration',
        'chapters/chapter11/section2-state-machines',
        'chapters/chapter11/section3-error-recovery',
        'chapters/chapter11/section4-final-project-deployment',
        'chapters/chapter11/section5-performance-optimization',
        'chapters/chapter11/section6-future-directions'
      ],
    },
  ],
};

export default sidebars;
